[build]
  publish = "exampleSite/public"
  command = "cd exampleSite && hugo --minify --gc --themesDir ../.."

[build.environment]
  HUGO_VERSION = "0.109.0"
  HUGO_THEME = "repo"
  HUGO_BASEURL = "/"

[[headers]]
  for = "/*" # This defines which paths this specific [[headers]] block will cover.

[headers.values]
  X-Frame-Options = "DENY"
  X-XSS-Protection = "1; mode=block"
  Referrer-Policy = "same-origin"
  Strict-Transport-Security = "max-age=31536000; includeSubDomains; preload"

[[redirects]]
  from = "/make-money/ways-to-make-money-online"
  to = "/blog/make-money-online"
  status = 301

[[redirects]]
  from = "/recommends/rakuten"
  to = "https://www.rakuten.com/r/JONESD1531?eeid=28187"
  status = 302

[[redirects]]
  from = "/recommends/starclick"
  to = "http://www.star-clicks.com/default?ref=513598"
  status = 302

[[redirects]]
  from = "/recommends/robinhood"
  to = "https://join.robinhood.com/dejuanj48/"
  status = 302

[[redirects]]
  from = "/recommends/coinbase"
  to = "https://www.coinbase.com/join/jones_rl5l"
  status = 302

[[redirects]]
  from = "/recommends/ibotta"
  to = "https://ibotta.onelink.me/iUfE/8cc13c64?friend_code=hycoajo"
  status = 302

[[redirects]]
  from = "/recommends/checkout51"
  to = "https://www.checkout51.com"
  status = 302

[[redirects]]
  from = "/recommends/media.net"
  to = "https://bit.ly/3LtuRRq"
  status = 302

[[redirects]]
  from = "/recommends/canva"
  to = "https://partner.canva.com/c/2747132/619765/10068"
  status = 302

[[redirects]]
  from = "/recommends/semrush"
  to = "https://semrush.sjv.io/c/2747132/995972/13053"
  status = 302

[[redirects]]
  from = "/recommends/instacart"
  to = "https://instacart.oloiyb.net/c/2747132/413183"
  status = 302

[[redirects]]
  from = "/recommends/buzzsprout"
  to = "https://www.buzzsprout.com/?referrer_id=17555302"
  status = 302

[[redirects]]
  from = "/recommends/fameswap"
  to = "https://fameswap.com/browse-tiktok-accounts-for-sale?ref=530854"
  status = 302

[[redirects]]
  from = "/recommends/famebolt"
  to = "https://famebolt.com?ref=3979"
  status = 302

[[redirects]]
  from = "/recommends/easyviral"
  to = "https://eazyviral.com/?ref=2000041"
  status = 302

[[redirects]]
  from = "/recommends/ysense"
  to = "https://www.ysense.com/?rb=104309769"
  status = 302

[[redirects]]
  from = "/recommends/getpaid"
  to = "https://www.get-paid.com/?ref=earnonlinemoney"
  status = 302

[[redirects]]
  from = "/recommends/freelancer"
  to = "https://www.freelancer.com/get/freelegitmonefve"
  status = 302

[[redirects]]
  from = "/recommends/inboxdollars"
  to = "https://www.inboxdollars.com?rb=106454892&ref_src=link"
  status = 302

[[redirects]]
  from = "/recommends/namecheap"
  to = "https://namecheap.pxf.io/g1ORqO"
  status = 302

[[redirects]]
  from = "/recommends/teachable"
  to = "https://teachable.sjv.io/EKE0Oe"
  status = 302

[[redirects]]
  from = "/recommends/shopify"
  to = "https://shopify.pxf.io/c/3661625/1728804/13624"
  status = 302

[[redirects]]
  from = "/recommends/neighbor"
  to = "https://neighbor.pxf.io/9WXmZe"
  status = 302

[[redirects]]
  from = "/recommends/coinsmart"
  to = "https://imp.i246982.net/c/3661625/794942/11346?trafsrc=Impact"
  status = 302

[[redirects]]
  from = "/recommends/network-solutions"
  to = "https://network-solutions.7eer.net/c/3661625/11311/555"
  status = 302

[[redirects]]
  from = "/recommends/domain-com"
  to = "https://domain.mno8.net/c/3661625/581154/9560"
  status = 302

[[redirects]]
  from = "/recommends/web-com"
  to = "https://web.yoxl.net/c/3661625/362108/1642"
  status = 302
