############# English navigation ##############

# main menu
[[main]]
name = "Home"
url = ""
weight = 1

[[main]]
name = "Guide"
url = "guide/"
weight = 2

[[main]]
name = "Make Money Online"
url = "blog/make-money-online/"
weight = 3

[[main]]
name = "Creative Side Hustles"
url = "blog/creative-side-hustles/"
weight = 4

[[main]]
name = "Passive Income Ideas"
url = "blog/passive-income-investments/"
weight = 5

[[main]]
name = "Blog"
url = "/blog"
weight = 6
hasChildren = false

# footer menu
[[footer]]
name = "Home"
url = "/"
weight = 1

[[footer]]
name = "About"
url = "about/"
weight = 2

[[footer]]
name = "Contact"
url = "contact/"
weight = 3

[[footer]]
name = "Privacy Policy"
url = "privacy-policy/"
weight = 4
