#################### default parameters ################################
# favicon
favicon = "images/favicon-i.png"
# logo
logo = "images/logo-front.png"
# use `x` with logo_width, example: "100x".
# Note: logo_width is not work with .svg file
logo_width = "150x"
# logo text will only show when logo is missing.
logo_text = "Earn Money Online"
# navbar fixed to top
navbar_fixed = false
# OpenGraph / Twitter Card metadata
description = "Find ways to earn money online via side hustles, work from home jobs, ebiz, along with other remote opportunities. Diversify your income today!"
author = "Dejuan Jones"
image = "images/money-logo.png" # this image will be used as fallback if a page has no image of its own
# contact info
address = "Seattle, Wa"
mobile = "+4252434038"
email = "earnonlinemoney2023@gmail.com"
# contact form action
contact_form_action = "https://formspree.io/f/xdoreeqg" # contact form works with https://formspree.io
# search
search = true

# Posts related Titles & Contents
categories_title = "Blog Categories"
posts_title = "Featured"
featured_post_title = "Featured Post"
recent_post_title = "Recent Post"
featured_post_button = "Featured"
recent_post_button = "Recent"
read_more_button = "Explore"
previous_button = "Previous"
next_button = "Next"
related_posts = "Related Posts"
showing_posts = "Showing Post From"
no_categories_found = "No Categories Found"
no_tags_found = "No Tags Found"

mainSections = ["blog"]
# about widget content
about_widget_content = "Connect with us on social media!"
# footer content
footer_content = "This platform is dedicated to empowering individuals from diverse backgrounds to embrace the digital realm and explore genuine avenues for financial success in the virtual world."
# custom script on header, example: custom_script= "<script>console.log(\"Hello World\")</script>"
custom_script= ""
# copyright
theme_copyright = true
copyright = "© Copyright"

# 404
error_404_text = "404 Page Not Found!"
error_404_button = "Back To Home"

# Preloader
[preloader]
enable = true
preloader = "" # use jpg, png, svg or gif format.

# Banner
[banner]
enable = true
title_large = "Earn Money Online **!**"
title_small = "Digital Side Hustles"
image = "images/earn-online-money.png"
background_image = "/images/banner-bg-shape.svg"
content = "Find ways to earn money online via side hustles, work from home jobs, ebiz, along with other remote opportunities. Diversify your income today!"
button_label = "Start Here"
button_link = "guide/"

# Advertise
[advertisement]
image = "images/earn-internet-income.png"
link = "https://earnonlinemoney.org/blog/make-money-online"

# cookies
[cookies]
enable = false
expire_days = 2
content = "This site uses cookies. By continuing to use this website, you agree to their use."
button = "I Accept"

######################## sidebar widgets #########################
[widgets]
sidebar = ["about", "categories", "recent-post", "newsletter"]
# available widget : about,categories,newsletter,recent-post


# Subscription
[subscription]
enable = true
newsletter_title = "Newsletter"
newsletter_invitation = "Join thousands of Tiny Salt subscribers and get our best recipes delivered each week!"
newsletter_placeholder = "Type And Hit Enter"
newsletter_reminder_a = "By Singing Up, You Agree To Receive Updated Content"
newsletter_reminder_b = "Privacy Policy"
newsletter_button = "Sign in"
# mailchimp subsciption
mailchimp_form_action = "https://gmail.us17.list-manage.com/subscribe/post" # replace this url with yours
mailchimp_form_name = "MERGE0" # replace this code with yours

############################# social site ########################
[[social]]
title = "facebook"
icon = "fab fa-facebook" # themify icon : https://themify.me/themify-icons
link = "https://www.facebook.com/earnmoneynowonline/"

[[social]]
title = "twitter"
icon = "fab fa-twitter" # themify icon : https://themify.me/themify-icons
link = "https://twitter.com/moneyonline_fre"

[[social]]
title = "instagram"
icon = "fab fa-instagram" # fontawesome icon pack : https://fontawesome.com/icons/
link = "#"

[[social]]
title = "github"
icon = "fab fa-github" # fontawesome icon pack : https://fontawesome.com/icons/
link = "#"

[[social]]
title = "linkedin"
icon = "fab fa-linkedin" # fontawesome icon pack : https://fontawesome.com/icons/
link = "https://linkedin.com/earn-money-online-free/"
